-- --------------------------------------------------------
-- Host:                         127.0.0.1
-- Versión del servidor:         5.5.42-MariaDB-log - MariaDB Server
-- SO del servidor:              Linux
-- HeidiSQL Versión:             8.3.0.4694
-- --------------------------------------------------------

/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET NAMES utf8 */;
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;

-- Volcando estructura para tabla mamonsoft.curso
DROP TABLE IF EXISTS `curso`;
CREATE TABLE IF NOT EXISTS `curso` (
  `oid` int(10) NOT NULL AUTO_INCREMENT,
  `nombre` text COLLATE latin1_spanish_ci NOT NULL,
  `descrip` text COLLATE latin1_spanish_ci NOT NULL,
  PRIMARY KEY (`oid`),
  KEY `oid` (`oid`)
) ENGINE=InnoDB AUTO_INCREMENT=23 DEFAULT CHARSET=latin1 COLLATE=latin1_spanish_ci;

-- Volcando datos para la tabla mamonsoft.curso: ~22 rows (aproximadamente)
/*!40000 ALTER TABLE `curso` DISABLE KEYS */;
INSERT INTO `curso` (`oid`, `nombre`, `descrip`) VALUES
	(1, 'Cloud Computación Tendencias y Aplicaciones', 'Descubre a lo largo de este curso cómo transformar radicalmente un negocio e innovar dentro de tu entorno a la vez que reduce tu tiempo. Aprende también cómo tener acceso a tu información en cualquier dispositivo y de forma segura.'),
	(2, 'Google Chrome y Alcances', 'Un navegador web desarrollado por Google y compilado con base en varios componentes e infraestructuras de desarrollo de aplicaciones (frameworks) de código abierto.'),
	(3, 'Google Búsquedas Básico y Avanzado', 'Un motor de búsqueda en la web propiedad de Google Inc., es el motor de búsqueda más utilizado en la Web, recibe cientos de millones de consultas cada día a través de sus diferentes servicios. El objetivo principal del buscador de Google es buscar texto en las páginas web.'),
	(4, 'Google Gmail Correo Electrónico', 'Es un servicio de correo electrónico con posibilidades POP3 e IMAP gratuito proporcionado por la empresa estadounidense Google.'),
	(5, 'Google Drive Básico + Conociendo la ofimática en la nube', 'Sistema basados en la administración de archivos y documentos más hojas de cálculos e imágenes y sonidos entre otros. Olvídate de los virus y pérdida de la información.'),
	(6, 'Google Ofimática Documentos', 'Administra tus documentos de libre acceso y a cualquier hora, adiós a la pérdida de la información y bienvenido al mundo de la administración de archivos colaboración y trabajo en equipo.'),
	(7, 'Google Ofimática Documentos Aplicado a la Administración', 'Conoce tu mundo de los documentos en la nube basados en la administración pública, cartas, memos, informes y manuales.'),
	(8, 'Google Ofimática Hoja de Cálculos', 'Una hoja de cálculo es un tipo de documento, que permite manipular datos numéricos y alfanuméricos dispuestos en forma de tablas compuestas por celdas (las cuales se suelen organizar en una matriz bidimensional de filas y columnas).'),
	(9, 'Google Ofimática Hoja de Cálculos Aplicado a la Administración Pública', 'Conoce el poder de los cálculos en la nube basados en la administración pública, estadísticas, planificación de presupuesto, nómina, descuento de ley y más.'),
	(10, 'Google Ofimática Presentación', 'Presenta tus trabajo y estadísticas, planes de negocio y explosiones a distancia y sobre la base de la seguridad.'),
	(11, 'Google Form', 'Crea formularios y administra contenido para encuestas y consultas a tus círculos, grupos.'),
	(12, 'Google Calendar Básico', 'Crear calendario y administra tú tiempo. Se organizado y puntual.'),
	(13, 'Google Calendar Avanzado. Jefe y/o Coordinadores de Proyectos', 'Crea grupos y colaboradores, eventos y reuniones administras el tiempo de tu personal a cargo.'),
	(14, 'Google redes sociales Google+, Eventos y Comunidades', 'Google+ (pronunciado y escrito también Google Plus, abreviado como G+ y en algunos países de lengua hispana pronunciado Google Más) es una red social operada por Google Inc.'),
	(15, 'Google Hangouts + YouTube', 'El poder de escribir en tiempo real en privado y por grupo crear comunidades y video llamados más conferencias.'),
	(16, 'Google Apps (keep, Giff, Traductor)', 'Herramientas de colaboración y administración diagramas de flujo, y traducción de contenidos.'),
	(17, 'Google Noticias, Maps, Earth', 'Noticias, Mapas y la tierra colabora ubicación y encuentra tus sitios preferidos y/o recomendados alimenta la red y administra tu tiempo de sitio a sito.'),
	(18, 'Google Blogger', 'Blogger es un servicio creado por Pyra Labs, y adquirido por Google en el año 2003, que permite crear y publicar una bitácora en línea. Para publicar contenidos, el usuario no tiene que escribir ningún código o instalar programas de servidor o de scripting.'),
	(19, 'Google Sitios Web', 'Esta aplicación permite crear un sitio web o una intranet de una forma tan sencilla como editar un documento. Con Google Sites los usuarios pueden reunir en un único lugar y de una forma rápida información variada, incluidosvídeos, calendarios, presentaciones, archivos adjuntos y texto. Además, permite compartir información con facilidad para verla y compartirla con un grupo reducido de colaboradores o con toda su organización, o con todo el mundo.'),
	(20, 'Google Seguridad', 'La privacidad de documentos sensibles puede ser comprometida por el hecho de que mucha gente está autenticada en sus cuentas de Google de forma casi permanente (las cuentas Google se utilizan para la gran variedad de servicios ofrecidos por Google como correo electrónico, calendario, etcétera). A pesar de que este login unificado tiene claras ventajas, representa un potencial riesgo para la seguridad mientras el acceso a Google Docs no requiera comprobación de contraseña.'),
	(21, 'Google Para Desarrolladores', 'Con el poder de los scripts al alcance de tus manos, macros en la web y desarrollo de sitios, php + google.'),
	(22, 'Google Web Toolkit o GWT', 'GWT o Google Web Toolkit es un framework creado por Google que permite ocultar la complejidad de varios aspectos de la tecnología AJAX. Es compatible con varios navegadores, lo cual es notorio ya que cada navegadorsuele necesitar código específico para lograr un front-end correcto en una aplicación web.');
/*!40000 ALTER TABLE `curso` ENABLE KEYS */;


-- Volcando estructura para tabla mamonsoft.nivel
DROP TABLE IF EXISTS `nivel`;
CREATE TABLE IF NOT EXISTS `nivel` (
  `oid` int(11) NOT NULL AUTO_INCREMENT,
  `nombre` text COLLATE latin1_spanish_ci NOT NULL,
  PRIMARY KEY (`oid`),
  KEY `oid` (`oid`)
) ENGINE=InnoDB AUTO_INCREMENT=11 DEFAULT CHARSET=latin1 COLLATE=latin1_spanish_ci;

-- Volcando datos para la tabla mamonsoft.nivel: ~10 rows (aproximadamente)
/*!40000 ALTER TABLE `nivel` DISABLE KEYS */;
INSERT INTO `nivel` (`oid`, `nombre`) VALUES
	(1, 'NO TIENE ESTUDIOS '),
	(2, 'PRIMARIA          '),
	(3, 'SECUNDARIA        '),
	(4, 'TECNICO MEDIO     '),
	(5, 'TECNICO SUPERIOR  '),
	(6, 'UNIVERSITARIO     '),
	(7, 'MAESTRIA          '),
	(8, 'DOCTORADO         '),
	(9, 'ESPECIALIDAD      '),
	(10, 'OTROS             ');
/*!40000 ALTER TABLE `nivel` ENABLE KEYS */;


-- Volcando estructura para tabla mamonsoft.ocupacion
DROP TABLE IF EXISTS `ocupacion`;
CREATE TABLE IF NOT EXISTS `ocupacion` (
  `oid` int(11) NOT NULL AUTO_INCREMENT,
  `nombre` text COLLATE latin1_spanish_ci NOT NULL,
  PRIMARY KEY (`oid`),
  KEY `oid` (`oid`)
) ENGINE=InnoDB AUTO_INCREMENT=197 DEFAULT CHARSET=latin1 COLLATE=latin1_spanish_ci;

-- Volcando datos para la tabla mamonsoft.ocupacion: ~196 rows (aproximadamente)
/*!40000 ALTER TABLE `ocupacion` DISABLE KEYS */;
INSERT INTO `ocupacion` (`oid`, `nombre`) VALUES
	(1, 'ABOGADO'),
	(2, 'ACTOR'),
	(3, 'ADMINISTRADOR'),
	(4, 'AERONAUTICO'),
	(5, 'AGRICULTOR'),
	(6, 'AGRIMENSOR'),
	(7, 'AGRONOMO'),
	(8, 'AJEDRECISTA'),
	(9, 'ALBANIL'),
	(10, 'ALGODONERO'),
	(11, 'AMA DE CASA'),
	(12, 'ANALISTA DE SISTEMAS'),
	(13, 'ANESTESIOLOGO'),
	(14, 'ANTROPOLOGO'),
	(15, 'APICULTOR'),
	(16, 'ARCHIVOLOGO'),
	(17, 'ARQUITECTO'),
	(18, 'ARROCERO'),
	(19, 'ASTROLOGO'),
	(20, 'ASTRONOMO'),
	(21, 'AVICULTOR'),
	(22, 'BAILARIN'),
	(23, 'BIBLIOTECOLOGO'),
	(24, 'BIOANALISTA'),
	(25, 'BIOLOGO'),
	(26, 'BIOQUIMICO'),
	(27, 'BUHONERO'),
	(28, 'BUZO'),
	(29, 'CAJERO'),
	(30, 'CALIGRAFO'),
	(31, 'CANTANTE'),
	(32, 'CARABANERO'),
	(33, 'CARNICERO'),
	(34, 'CARPINTERO'),
	(35, 'CAUCHERO'),
	(36, 'CERAMISTA'),
	(37, 'CERVECERO'),
	(38, 'CHOFER'),
	(39, 'CINEMATOGRAFO'),
	(40, 'CITOLOGO'),
	(41, 'CLERO'),
	(42, 'COBRADOR'),
	(43, 'COCINERO'),
	(44, 'COMERCIANTE'),
	(45, 'CONFECCIONISTA'),
	(46, 'CONSERJE'),
	(47, 'CONSERVACIONISTA'),
	(48, 'CONSTRUCTOR'),
	(49, 'CONTADOR PUBLICO'),
	(50, 'CONTROLADOR TRAFICO AEREO'),
	(51, 'COSMETOLOGO'),
	(52, 'CURANDERO'),
	(53, 'DECORADOR'),
	(54, 'DESPACHANTE ADUANA'),
	(55, 'DESTILADOR'),
	(56, 'DIPLOMATICO'),
	(57, 'DIRECTOR'),
	(58, 'DISENADOR'),
	(59, 'DOCENTE'),
	(60, 'DRAMATURGO'),
	(61, 'EBANISTA'),
	(62, 'ECONOMISTA'),
	(63, 'EDAFOLOGO'),
	(64, 'ELECTRICISTA'),
	(65, 'ELECTRONICO'),
	(66, 'EMPLEADO BANCARIO'),
	(67, 'EMPRESARIO'),
	(68, 'ENFERMERO'),
	(69, 'ESCRIBANO'),
	(70, 'ESCRITOR'),
	(71, 'FARMACEUTICO'),
	(72, 'FERROVIARIO'),
	(73, 'FILOSOFO'),
	(74, 'FISICO'),
	(75, 'FLORICULTOR'),
	(76, 'FONOAUDIOLOGO'),
	(77, 'FOTOGRAFO'),
	(78, 'FRIGORIFICO'),
	(79, 'FRUTICULTOR'),
	(80, 'GANADERO'),
	(81, 'GEOGRAFO'),
	(82, 'GEOLOGO'),
	(83, 'GRABADOR'),
	(84, 'GRUERO'),
	(85, 'GUARDAPARQUE'),
	(86, 'GUIA TURISTICO'),
	(87, 'HERRERO'),
	(88, 'HIDROGRAFO'),
	(89, 'HISTOLOGO'),
	(90, 'HISTORIADOR'),
	(91, 'HOMEOPATA'),
	(92, 'HORTICULTOR'),
	(93, 'ILUMINISTA'),
	(94, 'INFORMATICA'),
	(95, 'INGENIERO'),
	(96, 'INSTRUCTOR'),
	(97, 'INSTRUMENTISTA'),
	(98, 'JARDINERO'),
	(99, 'KINESIOLOGO'),
	(100, 'LABORATORISTA'),
	(101, 'LICORERIA'),
	(102, 'LINGUISTA'),
	(103, 'LOCUTOR'),
	(104, 'LUTHIER'),
	(105, 'MAESTRO'),
	(106, 'MANICURISTA'),
	(107, 'MAQUINISTA'),
	(108, 'MARINO MERCANT'),
	(109, 'MATEMATICO'),
	(110, 'MECANICO'),
	(111, 'MEDICO'),
	(112, 'MESONERO'),
	(113, 'METEOROLOGO'),
	(114, 'MOSAISTA'),
	(115, 'MOTORIZADO'),
	(116, 'MUSEOLOGO'),
	(117, 'MUSICO'),
	(118, 'NUTRICIONISTA'),
	(119, 'OBSTETRA'),
	(120, 'OCEANOGRAFO'),
	(121, 'ODONTOLOGO'),
	(122, 'OPTOMETRISTA'),
	(123, 'ORFEBRE'),
	(124, 'OTROS'),
	(125, 'PANADERO'),
	(126, 'PEDAGOGO'),
	(127, 'PEDICURISTA'),
	(128, 'PERIODISTA'),
	(129, 'PESCADOR'),
	(130, 'PILOTO COMERCI'),
	(131, 'PINTOR'),
	(132, 'PISCICULTOR'),
	(133, 'PODOLOGO'),
	(134, 'POLICIA FEDERA'),
	(135, 'POLICIA MUNICI'),
	(136, 'POLITICO'),
	(137, 'PREFECTO'),
	(138, 'PROCURADOR'),
	(139, 'PRODUCTOR'),
	(140, 'PROFESOR'),
	(141, 'PROGRAMADOR'),
	(142, 'PROMOTOR'),
	(143, 'PSICOLOGO'),
	(144, 'QUIMICO'),
	(145, 'RECEPCIONISTA'),
	(146, 'REDACTOR'),
	(147, 'RENTISTA'),
	(148, 'REPUJADOR'),
	(149, 'SECRETARIA'),
	(150, 'SILVICULTOR'),
	(151, 'SOCIOLOGO'),
	(152, 'TABACALERO'),
	(153, 'TALABARTERO'),
	(154, 'TAMBERO'),
	(155, 'TAPICERO'),
	(156, 'TAXIDERMISTA'),
	(157, 'TAXISTA'),
	(158, 'TEC. PETROQUIM'),
	(159, 'TEC. PLASTICO'),
	(160, 'TENISTA'),
	(161, 'TEOLOGO'),
	(162, 'TERAPISTA'),
	(163, 'TRADUCTOR'),
	(164, 'TRANSPORTISTA'),
	(165, 'VENDEDOR'),
	(166, ' VETERINARIO'),
	(167, 'VIGILANTE'),
	(168, 'VITICULTOR'),
	(169, 'YERBATERO'),
	(170, 'ZAPATERO'),
	(171, 'ESTUDIANTE'),
	(172, 'JUBILADOS'),
	(173, 'AEROMOZA'),
	(174, 'AUDITOR'),
	(175, 'BARMAN'),
	(176, 'BARRENDERO'),
	(177, 'CORREDOR DE SEGUROS'),
	(178, 'ENTRENADOR'),
	(179, 'ESTADISTICO'),
	(180, 'ESTILISTA'),
	(181, 'FISCAL'),
	(182, 'GUARDAESPALDAS'),
	(183, 'JINETE'),
	(184, 'MENSAJERO'),
	(185, 'MERCADEO'),
	(186, 'MILITAR'),
	(187, 'OFICINISTA'),
	(188, 'PARQUERO'),
	(189, 'PLOMERO'),
	(190, 'PUBLICISTA'),
	(191, 'RELACIONISTA PUBLICO'),
	(192, 'SERVICIO DOMESTICO'),
	(193, 'SOBRECARGO'),
	(194, 'TORERO'),
	(195, 'VISITADOR MEDICO'),
	(196, 'OBRERO');
/*!40000 ALTER TABLE `ocupacion` ENABLE KEYS */;


-- Volcando estructura para tabla mamonsoft.profesion
DROP TABLE IF EXISTS `profesion`;
CREATE TABLE IF NOT EXISTS `profesion` (
  `oid` int(10) NOT NULL AUTO_INCREMENT,
  `nombre` text COLLATE latin1_spanish_ci NOT NULL,
  PRIMARY KEY (`oid`),
  KEY `oid` (`oid`)
) ENGINE=InnoDB AUTO_INCREMENT=108 DEFAULT CHARSET=latin1 COLLATE=latin1_spanish_ci;

-- Volcando datos para la tabla mamonsoft.profesion: ~107 rows (aproximadamente)
/*!40000 ALTER TABLE `profesion` DISABLE KEYS */;
INSERT INTO `profesion` (`oid`, `nombre`) VALUES
	(1, 'Abogado'),
	(2, 'Abogado (a)'),
	(3, 'Analista de Sistemas'),
	(4, 'Antropólogo'),
	(5, 'Criminólogo'),
	(6, 'Economista'),
	(7, 'Farmacéutico'),
	(8, 'Ingeniero Agroindustrial'),
	(9, 'Ingeniero Agrónomo'),
	(10, 'Ingeniero de Materiales'),
	(11, 'Ingeniero de Minas'),
	(12, 'Ingeniero de Petróleo'),
	(13, 'Ingeniero de Recursos Naturales Renovables'),
	(14, 'Ingeniero de Sistemas'),
	(15, 'Ingeniero Electricista'),
	(16, 'Ingeniero Eléctrico'),
	(17, 'Ingeniero Electrónico de Computación'),
	(18, 'Ingeniero en Informática'),
	(19, 'Ingeniero Forestal'),
	(20, 'Ingeniero Geodesta'),
	(21, 'Ingeniero Geólogo'),
	(22, 'Ingeniero Metalúrgico'),
	(23, 'Licenciado (a) en Administracion de Empresas'),
	(24, 'Licenciado (a) en Administración de Empresas de Diseño'),
	(25, 'Licenciado (a) en Administración Mención Empresas Agropecuarias'),
	(26, 'Licenciado (a) en Administracion Publica'),
	(27, 'Licenciado (a) en Artes'),
	(28, 'Licenciado (a) en Artes Plásticas'),
	(29, 'Licenciado (a) en Artes Visuales'),
	(30, 'Licenciado (a) en Bioanálisis'),
	(31, 'Licenciado (a) en Biologia'),
	(32, 'Licenciado (a) en Ciencias Actuariales'),
	(33, 'Licenciado (a) en Ciencias Estadísticas'),
	(34, 'Licenciado (a) en Ciencias Políticas y Administrativas'),
	(35, 'Licenciado (a) en Computación'),
	(36, 'Licenciado (a) en Contaduria Publica'),
	(37, 'Licenciado (a) en Contaduría Pública'),
	(38, 'Licenciado (a) en Diseño Gráfico'),
	(39, 'Licenciado (a) en Economía de la Ind. Forestal'),
	(40, 'Licenciado (a) en Educacion'),
	(41, 'Licenciado (a) en Educación Física, Deporte y Recreación'),
	(42, 'Licenciado (a) en Educacion Integral'),
	(43, 'Licenciado (a) en Educación Mención Agropecuaria Rural y Comunitaria'),
	(44, 'Licenciado (a) en Educación mención Biología y Química'),
	(45, 'Licenciado (a) en Educación mención Castellano y Literatura'),
	(46, 'Licenciado (a) en Educacion Mencion Ciencias Fisico Naturales'),
	(47, 'Licenciado (a) en Educación Mención Ciencias Sociales'),
	(48, 'Licenciado (a) en Educación Mención Ecología y Educación Ambiental'),
	(49, 'Licenciado (a) en Educación mención Física y Matématicas'),
	(50, 'Licenciado (a) en Educación Mención Geografía y Ciencias de la Tierra'),
	(51, 'Licenciado (a) en Educación Mención Geografía y Ciencias de la Tierra'),
	(52, 'Licenciado (a) en Educación Mención Historia'),
	(53, 'Licenciado (a) en Educación Mención Química'),
	(54, 'Licenciado (a) en Enfermeria'),
	(55, 'Licenciado (a) en Estudios Ambientales'),
	(56, 'Licenciado (a) en Estudios Internacionales'),
	(57, 'Licenciado (a) en Estudios Políticos y Administrativos'),
	(58, 'Licenciado (a) en Estudios Políticos y Administrativos'),
	(59, 'Licenciado (a) en Fisica'),
	(60, 'Licenciado (a) en Geografía'),
	(61, 'Licenciado (a) en Geoquímica'),
	(62, 'Licenciado (a) en Gerencia Agroindustrial'),
	(63, 'Licenciado (a) en Historia'),
	(64, 'Licenciado (a) en Informatica'),
	(65, 'Licenciado (a) en Matematica'),
	(66, 'Licenciado (a) en Matematica Mencion Docencia Matematica'),
	(67, 'Licenciado (a) en Música'),
	(68, 'Licenciado (a) en Nutrición y Dietética'),
	(69, 'Licenciado (a) en Psicología'),
	(70, 'Licenciado (a) en Sociología'),
	(71, 'Licenciado (a) en Trabajo Social'),
	(72, 'Médico Cirujano</option>'),
	(73, 'Médico Veterinario'),
	(74, 'Politologo (a)'),
	(75, 'Profesor (a)'),
	(76, 'Profesor de Artes Industriales'),
	(77, 'Sociólogo'),
	(78, 'Técnico Superior Cardiopulmonar'),
	(79, 'Técnico Superior en Radiodiagnóstico'),
	(80, 'Tecnólogo en Estadística'),
	(81, 'Tecnólogo en Sistemas Industriales'),
	(82, 'TSU en Administracion de Empresas'),
	(83, 'TSU en Administración: Contaduría'),
	(84, 'TSU en Agroindustrial'),
	(85, 'TSU en Análisis y Diseño de Sistemas'),
	(86, 'TSU en Análisis y Diseño de Sistemas'),
	(87, 'TSU en Comunicaciones y Electrónica'),
	(88, 'TSU en Construcción Civil'),
	(89, 'TSU en Contabilidad Computarizada'),
	(90, 'TSU en Controles Automáticos'),
	(91, 'TSU en Diseño Ambiental'),
	(92, 'TSU en Diseño Gráfico'),
	(93, 'TSU en Electricidad'),
	(94, 'TSU en Enfermeria'),
	(95, 'TSU en Estadistica de Salud'),
	(96, 'TSU en Hotelería'),
	(97, 'TSU en Informática'),
	(98, 'TSU en Manejo de Emergencia y Acción Contra Desastres'),
	(99, 'TSU en Mantenimiento de Equipos Eléctricos'),
	(100, 'TSU en Petróleo'),
	(101, 'TSU en Psicopedagogía'),
	(102, 'TSU en Radiología e Imagenología'),
	(103, 'TSU en Sistemas de Información'),
	(104, 'TSU en Tecnología Agropecuaria'),
	(105, 'TSU en Tecnología Ambiental'),
	(106, 'TSU en Tecnología de Recursos Naturales Renovables'),
	(107, 'TSU en Turismo');
/*!40000 ALTER TABLE `profesion` ENABLE KEYS */;


-- Volcando estructura para tabla mamonsoft.solicitud_curso
DROP TABLE IF EXISTS `solicitud_curso`;
CREATE TABLE IF NOT EXISTS `solicitud_curso` (
  `oid` int(10) NOT NULL AUTO_INCREMENT,
  `nombres` varchar(50) COLLATE latin1_spanish_ci NOT NULL,
  `apellidos` varchar(50) COLLATE latin1_spanish_ci NOT NULL,
  `correo` varchar(50) COLLATE latin1_spanish_ci NOT NULL,
  `telefonos` varchar(50) COLLATE latin1_spanish_ci NOT NULL,
  `observacion` text COLLATE latin1_spanish_ci NOT NULL,
  `curso` int(10) NOT NULL,
  `nivel` int(10) NOT NULL,
  `ocupacion` int(10) NOT NULL,
  `profesion` int(10) NOT NULL,
  `cedula` int(10) NOT NULL,
  PRIMARY KEY (`oid`),
  KEY `oid` (`oid`),
  KEY `curso` (`curso`),
  KEY `nivel` (`nivel`),
  KEY `ocupacion` (`ocupacion`),
  KEY `profesion` (`profesion`),
  KEY `cedula` (`cedula`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1 COLLATE=latin1_spanish_ci;

-- Volcando datos para la tabla mamonsoft.solicitud_curso: ~0 rows (aproximadamente)
/*!40000 ALTER TABLE `solicitud_curso` DISABLE KEYS */;
/*!40000 ALTER TABLE `solicitud_curso` ENABLE KEYS */;
/*!40101 SET SQL_MODE=IFNULL(@OLD_SQL_MODE, '') */;
/*!40014 SET FOREIGN_KEY_CHECKS=IF(@OLD_FOREIGN_KEY_CHECKS IS NULL, 1, @OLD_FOREIGN_KEY_CHECKS) */;
/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
